
environment:
  matrix:
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda3

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION%"
  - activate test-environment
  - pip install -e .
  - pip install cx_Freeze
  - pip install fbs
  - pip install pytest
  - pip install schema
  - ps: Start-FileDownload 'https://www.sqlite.org/2019/sqlite-dll-win32-x86-3280000.zip'
  - unzip sqlite-dll-win32-x86-3280000.zip
  - cd fbs
  - fbs freeze
  - cp -R ..\cutevariant\ target\cutevariant\
  #- copy sqlite3.dll C:\Miniconda3\envs\test-environment\DLLs\
  #- python make_a_blob.py build_exe

artifacts:
  - path: fbs
    name: cutevariant

  
build: off

test_script:
  - python -m pytest -vs tests

