language: python
addons:
  apt:
    packages:
    - x11-utils
    - libxkbcommon-x11-0
os:
  - linux

python:
  - "3.6"
variables:
  QT_QPA_PLATFORM: "offscreen"




# command to install dependencies
install:
  - make install_deps

# command to run tests
script:
  - QT_DEBUG_PLUGINS=1 python -m pytest tests -sv
