notifications:
  email: false
addons:
  apt:
    packages:
    - x11-utils
    - libxkbcommon-x11-0
services: xvfb
matrix:
 include:
 - os: osx
   language: generic
   env: MAC_PYTHON_VERSION=3.6
   sudo: required
 - os: linux
   language: python
   python: 3.6:
install:
  - make install_deps

# command to run tests
script:
  - python -m pytest tests -vv
