language: python
# addons:
#   apt:
#     packages:
#     - libxcb-xkb1
#     - x11-utils
#     - libxkbcommon-x11-0
os:
  - linux


python:
  - "3.6"
variables:
  QT_QPA_PLATFORM: "offscreen"


before_install:
  - sudo apt-get install -y libxkbcommon-x11-0 x11-utils

# command to install dependencies
install:
  - make install_deps

# command to run tests
script:
  - python -m pytest tests -vv
