language: python

os:
  - linux

python:
  - "3.6"
variables:
  QT_QPA_PLATFORM: "offscreen"

addons:
  apt:
    packages:
    - x11-utils
    - libxkbcommon-x11-0

# command to install dependencies
install:
  - make install_deps

# command to run tests
script:
  - python -m pytest cutevariant tests -vv
